apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dummy
    app.kubernetes.io/instance: dummy-instance
    app.kubernetes.io/version: '1.29'
    app.kubernetes.io/managed-by: kubectl
  name: dummy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers:
        - image: 235501828783.dkr.ecr.us-east-2.amazonaws.com/dummy:latest
          imagePullPolicy: Always
          name: cicd-demo
          ports:
            - containerPort: 3000
 
