apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: dummy
    app.kubernetes.io/instance: dummy instance
    app.kubernetes.io/version: "1.29"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: cicd-demo
spec:
  selector:
    app: dummy
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
